### ISSUE TITLE
No module named 'cv2'

### ISSUE THREAD

**Issue by ycdaskin** [vlarobbyk/opencv-tinker-board#1]
Hello,

After succesfull build i am getting this error when i try to import cv2. 
There are some mistakes in these steps. First, we have to install numpy before building opnecv but there is no such a step. Second opencv and contrib module directories are not constant. They depend on user's user name or directory naming. So cmake flags change for every user.

And there are some questions:

1. Why do we have to use Berryconda?
2. Why do we have to work on a virtual environment?
3. Why do we have to install python 3 again? It is already pre installed for all tinkerboard operating systems.
4. Where is my python installation? I cannot use it even i work on the virtual environment.

**Comment by vlarobbyk** [comment]
Hello! I am so sorry for the late responde, I was very busy. Yes, I am agree with you, each user must to set their directories. Following, I provide some answers:

1. I am using Berryconda because for me is more is more comfortable managing virtual environments with this tool. In second place, I wanted to test if is possible to use Berryconda with a different microcomputer than Raspberry PI.
2.  In my experience, when you start a new project, is easy to delete a virtual environment if you commit some mistake during libraries installation. Conversely, if you install bad libraries without a virtual environment it will difficult to correct the errors in your root installation.
3. Yes, Python is preinstalled, however I am installing it in the virtual environment.
4. Commonly is in your home (~/).
